---
- hosts: 127.0.0.1
  connection: local

  vars:
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEA0USmj/khKnAmpgeLVlbB6itFr+4/ok2z7sbtEKtZZY+19a3D7fE8F1PU5z1kWALIvRo7p/3kkEN8FCKv86cS8jCv82B5OXhAeLgU/oisCXsIrCvQMbPyUKl7bNx4u3BA8HjtCVsOE6zzzvKG6BXKdNTJqbDMNIY33CkDcj1uWo8Buh5WgUxjvnP5YBmqdPHX1I8E7QLL+d5H6bdUCPQ71URY2cmqvO4IoMwuxrOBJ3c9Ucsw3GCwaNHoPIEkOuTKpRbI951ovqkjDH9/PQgox0HFZ2G1srSS/fPrJizrhJTDjsj5OMFpxbpv0zptMosrStM0MFEBkHRzu6p7b/LHTcNtIHM6OQSqw7DG/07dfXXNrhiqyrZLYg019rYJxN+fOzEdm121aLw/SIOKOzVh3hQuVC7rq4yIdvZXu+W/RRKylYkChpWOsABWqjfCY/bMHpU0+PnFIbCoua/1ZoovTMXsYYtxto/6xGysuVovO0fxYFoxvk54K4TtnO59GCo9UUgQBC+HIqtUW3ycP2lOvjfA6iY3DPGYDvlSG8FhxcMVuWfZ3UYEiUfPYFqzuygf2RgUXI6gFtIHeqsO7kXQ1ii28yXM69rcNoTjD/xeb5u+42u+szwccAYcsXzn5C1BB0CGBhUtHzzUm9+Qiby03KvKgWl8287GIk1/9QlATYk="

  tasks:
  - name: Add php repo
    apt_repository:
      repo: 'ppa:ondrej/php'

  # В контектсе безопасности пароль задаётся через секреты, vault, параметр при запуске ansible-playbook (--extra-vars).
  # В данном случае для "простоты" и скорости написания пароль задан в плейбуке.
  - name: Add the user Ubuntu
    user:
      name: ubuntu
      password: "{{ 'Abcdef45' | password_hash('sha512') }}"
      groups: sudo
      append: true

  - name: Add user Ubuntu sudo permissions without password
    lineinfile:
      dest: "/etc/sudoers"
      line: 'ubuntu      ALL=(ALL) NOPASSWD:ALL'

  - name: Add ssh key autorization
    lineinfile:
      dest: "/home/ubuntu/.ssh/authorized_keys"
      line: "{{ ssh_key }}"
      create: true

  - name: Update and install soft
    apt:
      update_cache: true
      name:
      - nginx
      - php7.4
      - php7.4-fpm
      - php7.4-mbstring
      - php7.4-xml
      - mysql-server
      - default-libmysqlclient-dev
      - git
      - curl
      - php7.4-cli
      - php7.4-mbstring
      - unzip
      state: latest

  - name: Download composer
    command: curl -sS https://getcomposer.org/installer -o composer-setup.php

  - name: Install composer
    command: php composer-setup.php --install-dir=/usr/local/bin --filename=composer

  - name: Allow SSH
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 22
      ctstate: NEW
      jump: ACCEPT
      comment: Allow SSH

  - name: Allow HTTP
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 80
      ctstate: NEW
      jump: ACCEPT
      comment: Allow HTTP

  - name: Allow HTTPS
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 443
      ctstate: NEW
      jump: ACCEPT
      comment: Allow HTTPS

  - block:
    - name: Clone github laravel repo
      git:
        repo: https://github.com/laravel/laravel.git
        dest: "/home/ubuntu/laravel"
        version: 8.x

    - name: Install laravel project
      command: composer install
      args:
        chdir: "/home/ubuntu/laravel"

    become: true
    become_user: ubuntu

  - name: Add nginx config
    copy:
        src: "./somedomain.company.conf"
        dest: "/etc/nginx/conf.d/"
        mode: 0644

  - name: Restart nginx
    service:
        name: nginx
        enabled: true
        state: restarted